# Nombre del servidor 
servidor.nombre=
# Usuario para la conexi\uFFFDn
servidor.usuario =uh
# Password para la conexi\uFFFDn
servidor.password=admin123
# Puerto de Conexi\uFFFDn
servidor.port=1433
# Nombre Base datos
bd.name=hos
# Controlador de SqlServer
servidor.control=jdbc:sqlserver
# Ip Servidor
ip=localhost